const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const ts = require('typescript');
const { normalizeApiBody } = require('./api-envelope');

const secret = 'auth-me-test-secret-only';
const user = { id: 'user-123', email: 'user@example.test', is_active: true };

function load(file, dependencies, globals = {}) {
  const source = fs.readFileSync(path.join(__dirname, file), 'utf8');
  const { outputText } = ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 }
  });
  const exports = {};
  vm.runInNewContext(outputText, {
    exports, require: name => {
      assert.ok(Object.hasOwn(dependencies, name), `Unexpected dependency: ${name}`);
      return dependencies[name];
    },
    Response, TextEncoder, ...globals
  });
  return exports;
}

async function setup(result = { data: user, error: null }) {
  const jose = await import('jose');
  const logs = [];
  const console = Object.fromEntries(['log', 'error', 'warn', 'info', 'debug'].map(
    method => [method, (...args) => logs.push(args)]
  ));
  const jwt = load('jwt.js', { jose }, { console, process: { env: { JWT_SECRET: secret } } });
  const calls = [];
  const query = {
    select(fields) { calls.push(['select', fields]); return this; },
    eq(field, value) { calls.push(['eq', field, value]); return this; },
    async maybeSingle() { calls.push(['maybeSingle']); return result; }
  };
  const { GET } = load('../app/api/v1/auth/me/route.js', {
    '@/lib/api-envelope': { normalizeApiBody },
    '@/lib/jwt': jwt,
    '@/lib/supabase': { supabase: { from(table) { calls.push(['from', table]); return query; } } }
  }, { console });
  async function token(payload, options = {}) {
    return new jose.SignJWT(payload)
      .setProtectedHeader({ alg: 'HS256' })
      .setExpirationTime(options.exp ?? '1h')
      .sign(new TextEncoder().encode(options.secret ?? secret));
  }
  async function call(value, cookie = false) {
    const response = await GET({
      headers: new Headers(value && !cookie ? { authorization: `Bearer ${value}` } : {}),
      cookies: { get: name => cookie && name === 'auth-token' ? { value } : undefined }
    });
    return { status: response.status, body: await response.json() };
  }
  return { jwt, token, call, calls, logs };
}

test('GET /auth/me resolves the signed id, regardless of email or sub', async () => {
  const ctx = await setup();
  const response = await ctx.call(await ctx.token({ id: user.id, email: 'other@example.test', sub: 'other-user' }));
  assert.equal(response.status, 200);
  assert.deepEqual(response.body.data.user, user);
  assert.deepEqual(ctx.calls.filter(call => call[0] === 'eq'), [['eq', 'id', user.id]]);
  assert.deepEqual(ctx.calls.filter(call => call[0] === 'from'), [['from', 'users']]);
});

test('GET /auth/me accepts tokens generated by the existing JWT utility and cookie transport', async () => {
  const ctx = await setup();
  const response = await ctx.call(await ctx.jwt.generateToken(user), true);
  assert.equal(response.status, 200);
  assert.deepEqual(response.body.data.user, user);
});

test('GET /auth/me rejects missing, malformed, incorrectly signed and expired JWTs before querying', async () => {
  const ctx = await setup();
  for (const value of [null, 'invalid-token',
    await ctx.token({ id: user.id }, { secret: 'wrong-secret' }),
    await ctx.token({ id: user.id }, { exp: Math.floor(Date.now() / 1000) - 600 })]) {
    const response = await ctx.call(value);
    assert.equal(response.status, 401);
    assert.equal(response.body.data, null);
  }
  assert.deepEqual(ctx.calls, []);
});

test('GET /auth/me rejects invalid id claims before querying', async () => {
  const ctx = await setup();
  for (const id of [undefined, null, '', '   ', false, [], {}, 0, -1, 1.5, Number.MAX_SAFE_INTEGER + 1]) {
    const response = await ctx.call(await ctx.token(id === undefined ? {} : { id }));
    assert.equal(response.status, 401, `id: ${JSON.stringify(id)}`);
    assert.equal(response.body.data, null);
    assert.deepEqual(response.body.mensagens, ['Token inválido']);
  }
  assert.deepEqual(ctx.calls, []);
});

test('GET /auth/me preserves positive integer ids without coercion', async () => {
  const ctx = await setup({ data: { ...user, id: 123 }, error: null });
  const response = await ctx.call(await ctx.token({ id: 123 }));
  assert.equal(response.status, 200);
  assert.deepEqual(ctx.calls.filter(call => call[0] === 'eq'), [['eq', 'id', 123]]);
});

test('GET /auth/me rejects inactive users without returning their profile', async () => {
  const ctx = await setup({ data: { ...user, is_active: false }, error: null });
  const response = await ctx.call(await ctx.token({ id: user.id }));
  assert.equal(response.status, 401);
  assert.deepEqual(response.body, { data: null, mensagens: ['Usuário inativo'] });
});

test('GET /auth/me returns 404 only when the user is missing', async () => {
  const ctx = await setup({ data: null, error: null });
  const response = await ctx.call(await ctx.token({ id: user.id }));
  assert.equal(response.status, 404);
  assert.equal(response.body.data, null);
  assert.deepEqual(response.body.mensagens, ['Usuário não encontrado']);
});

test('GET /auth/me returns 500 for database errors without exposing details', async () => {
  const ctx = await setup({ data: null, error: { code: '42703', message: 'column users.address does not exist' } });
  const response = await ctx.call(await ctx.token({ id: user.id }));
  assert.equal(response.status, 500);
  assert.deepEqual(response.body, { data: null, mensagens: ['Erro ao consultar usuário'] });
});

test('GET /auth/me requests only the supported profile fields', async () => {
  const ctx = await setup();
  await ctx.call(await ctx.token({ id: user.id }));
  const fields = ctx.calls.find(call => call[0] === 'select')[1].split(',').map(field => field.trim());
  assert.deepEqual(fields, ['id', 'email', 'full_name', 'role', 'phone', 'birth_date', 'created_at', 'last_login', 'is_active']);
  assert.ok(ctx.calls.some(call => call[0] === 'maybeSingle'));
});

test('GET /auth/me does not log credentials, JWT payloads or profiles', async () => {
  const ctx = await setup();
  const value = await ctx.token({ id: user.id, email: user.email });
  ctx.logs.length = 0;
  await ctx.call(value);
  await ctx.call(value, true);
  const logs = JSON.stringify(ctx.logs);
  for (const sensitive of [value, user.id, user.email, JSON.stringify(user)]) {
    assert.equal(logs.includes(sensitive), false, sensitive);
  }
});
